name: tabby_gateway
description: A new Flutter package project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1
homepage:

environment:
  sdk: '>=2.17.1 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  tabby_flutter_inapp_sdk: ^1.4.0
  payment_base:
    path: ../payment_base
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  http: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  assets:
    - assets/images/

